### ISSUE TITLE
Heroku deployment is down

### ISSUE THREAD

**Issue by jaredwhanisch** [paigeegorry/last-airbender-api#10]
It looks like Heroku has started to enforce no longer offering a free tier. If you don't want to pay for Heroku, [here are some other free options](https://www.makeuseof.com/heroku-alternatives-free-full-stack-hosting/) to deploy to if you'd like!

**Comment by paigeegorry** [comment]
Thanks @jaredwhanisch! I'm working on a new deploy now, was away for the holidays. Thanks for linking some resources! 🙏

**Comment by paigeegorry** [comment]
@jaredwhanisch Deployed to fly.io! https://last-airbender-api.fly.dev/ Closing this issue
