### ISSUE TITLE
Making it easier to update the content

### ISSUE THREAD

**Issue by d3xt3r0** [paigeegorry/last-airbender-api#8]
Make the content better by adding short description in the API and allowing people to update the content easily like with the pokedex repo. 

Thanks

**Comment by paigeegorry** [comment]
@d3xt3r0 Would love some more detailed context around what you are looking for. Short description on contributing? I don't own the pokedex repo, so I am not sure what you are referencing. Would love to make changes to make things easier. Let me know.

**Comment by paigeegorry** [comment]
Closing this issue for now as there was no specific action items.
